

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class NLAddressOrderType : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.NLAddressOrderType, global::LightSwitchApplication.NLAddressOrderType.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the NLAddressOrderType entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public NLAddressOrderType()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public NLAddressOrderType(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.NLAddressOrderType> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.NLAddressOrderType.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NLAddressOrderType_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NLAddressOrderType_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.NLAddressOrderType.DetailsClass.GetValue(this, global::LightSwitchApplication.NLAddressOrderType.DetailsClass.PropertySetProperties.Id);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Name
        {
            get
            {
                return global::LightSwitchApplication.NLAddressOrderType.DetailsClass.GetValue(this, global::LightSwitchApplication.NLAddressOrderType.DetailsClass.PropertySetProperties.Name);
            }
            set
            {
                global::LightSwitchApplication.NLAddressOrderType.DetailsClass.SetValue(this, global::LightSwitchApplication.NLAddressOrderType.DetailsClass.PropertySetProperties.Name, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Prison> Prisons
        {
            get
            {
                return global::LightSwitchApplication.NLAddressOrderType.DetailsClass.GetValue(this, global::LightSwitchApplication.NLAddressOrderType.DetailsClass.PropertySetProperties.Prisons);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Prison> PrisonsQuery
        {
            get
            {
                return global::LightSwitchApplication.NLAddressOrderType.DetailsClass.GetQuery(this, global::LightSwitchApplication.NLAddressOrderType.DetailsClass.PropertySetProperties.Prisons);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.NLAddressOrderType,
                global::LightSwitchApplication.NLAddressOrderType.DetailsClass,
                global::LightSwitchApplication.NLAddressOrderType.DetailsClass.IImplementation,
                global::LightSwitchApplication.NLAddressOrderType.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.NLAddressOrderType, global::LightSwitchApplication.NLAddressOrderType.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.NLAddressOrderType, global::LightSwitchApplication.NLAddressOrderType.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.NLAddressOrderType.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.NLAddressOrderType, global::LightSwitchApplication.NLAddressOrderType.DetailsClass>.Entry
                __NLAddressOrderTypeEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.NLAddressOrderType, global::LightSwitchApplication.NLAddressOrderType.DetailsClass>.Entry(
                    global::LightSwitchApplication.NLAddressOrderType.DetailsClass.__NLAddressOrderType_CreateNew,
                    global::LightSwitchApplication.NLAddressOrderType.DetailsClass.__NLAddressOrderType_Created,
                    global::LightSwitchApplication.NLAddressOrderType.DetailsClass.__NLAddressOrderType_AllowSaveWithErrors);
            private static global::LightSwitchApplication.NLAddressOrderType __NLAddressOrderType_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.NLAddressOrderType> es)
            {
                return new global::LightSwitchApplication.NLAddressOrderType(es);
            }
            private static void __NLAddressOrderType_Created(global::LightSwitchApplication.NLAddressOrderType e)
            {
                e.NLAddressOrderType_Created();
            }
            private static bool __NLAddressOrderType_AllowSaveWithErrors(global::LightSwitchApplication.NLAddressOrderType e)
            {
                bool result = false;
                e.NLAddressOrderType_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.NLAddressOrderType, global::LightSwitchApplication.NLAddressOrderType.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.NLAddressOrderType, global::LightSwitchApplication.NLAddressOrderType.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.NLAddressOrderType.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.NLAddressOrderType, global::LightSwitchApplication.NLAddressOrderType.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.NLAddressOrderType, global::LightSwitchApplication.NLAddressOrderType.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.NLAddressOrderType.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.NLAddressOrderType, global::LightSwitchApplication.NLAddressOrderType.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.NLAddressOrderType, global::LightSwitchApplication.NLAddressOrderType.DetailsClass, string> Name
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.NLAddressOrderType.DetailsClass.PropertySetProperties.Name) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.NLAddressOrderType, global::LightSwitchApplication.NLAddressOrderType.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.NLAddressOrderType, global::LightSwitchApplication.NLAddressOrderType.DetailsClass, global::LightSwitchApplication.Prison> Prisons
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.NLAddressOrderType.DetailsClass.PropertySetProperties.Prisons) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.NLAddressOrderType, global::LightSwitchApplication.NLAddressOrderType.DetailsClass, global::LightSwitchApplication.Prison>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; }
                new string Name { get; set; }
                new global::System.Collections.IEnumerable Prisons { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.NLAddressOrderType, global::LightSwitchApplication.NLAddressOrderType.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.NLAddressOrderType, global::LightSwitchApplication.NLAddressOrderType.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.NLAddressOrderType.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.NLAddressOrderType.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.NLAddressOrderType.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.NLAddressOrderType.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.NLAddressOrderType.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.NLAddressOrderType.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.NLAddressOrderType, global::LightSwitchApplication.NLAddressOrderType.DetailsClass, int>.Data> c, global::LightSwitchApplication.NLAddressOrderType.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.NLAddressOrderType e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.NLAddressOrderType e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.NLAddressOrderType.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.NLAddressOrderType e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.NLAddressOrderType, global::LightSwitchApplication.NLAddressOrderType.DetailsClass, string>.Entry
                    Name = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.NLAddressOrderType, global::LightSwitchApplication.NLAddressOrderType.DetailsClass, string>.Entry(
                        "Name",
                        global::LightSwitchApplication.NLAddressOrderType.DetailsClass.PropertySetProperties._Name_Stub,
                        global::LightSwitchApplication.NLAddressOrderType.DetailsClass.PropertySetProperties._Name_ComputeIsReadOnly,
                        global::LightSwitchApplication.NLAddressOrderType.DetailsClass.PropertySetProperties._Name_Validate,
                        global::LightSwitchApplication.NLAddressOrderType.DetailsClass.PropertySetProperties._Name_GetImplementationValue,
                        global::LightSwitchApplication.NLAddressOrderType.DetailsClass.PropertySetProperties._Name_SetImplementationValue,
                        global::LightSwitchApplication.NLAddressOrderType.DetailsClass.PropertySetProperties._Name_OnValueChanged);
                private static void _Name_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.NLAddressOrderType.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.NLAddressOrderType, global::LightSwitchApplication.NLAddressOrderType.DetailsClass, string>.Data> c, global::LightSwitchApplication.NLAddressOrderType.DetailsClass d, object sf)
                {
                    c(d, ref d._Name, sf);
                }
                private static bool _Name_ComputeIsReadOnly(global::LightSwitchApplication.NLAddressOrderType e)
                {
                    bool result = false;
                    e.Name_IsReadOnly(ref result);
                    return result;
                }
                private static void _Name_Validate(global::LightSwitchApplication.NLAddressOrderType e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Name_Validate(r);
                }
                private static string _Name_GetImplementationValue(global::LightSwitchApplication.NLAddressOrderType.DetailsClass d)
                {
                    return d.ImplementationEntity.Name;
                }
                private static void _Name_SetImplementationValue(global::LightSwitchApplication.NLAddressOrderType.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Name = v;
                }
                private static void _Name_OnValueChanged(global::LightSwitchApplication.NLAddressOrderType e)
                {
                    e.Name_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.NLAddressOrderType, global::LightSwitchApplication.NLAddressOrderType.DetailsClass, global::LightSwitchApplication.Prison>.Entry
                    Prisons = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.NLAddressOrderType, global::LightSwitchApplication.NLAddressOrderType.DetailsClass, global::LightSwitchApplication.Prison>.Entry(
                        "Prisons",
                        global::LightSwitchApplication.NLAddressOrderType.DetailsClass.PropertySetProperties._Prisons_Stub,
                        global::LightSwitchApplication.NLAddressOrderType.DetailsClass.PropertySetProperties._Prisons_GetReferencedEntities,
                        global::LightSwitchApplication.NLAddressOrderType.DetailsClass.PropertySetProperties._Prisons_GetEntityCollection);
                private static void _Prisons_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.NLAddressOrderType.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.NLAddressOrderType, global::LightSwitchApplication.NLAddressOrderType.DetailsClass, global::LightSwitchApplication.Prison>.Data> c, global::LightSwitchApplication.NLAddressOrderType.DetailsClass d, object sf)
                {
                    c(d, ref d._Prisons, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Prison> _Prisons_GetReferencedEntities(global::LightSwitchApplication.NLAddressOrderType.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Prison, global::LightSwitchApplication.Prison.DetailsClass>(global::LightSwitchApplication.NLAddressOrderType.DetailsClass.PropertySetProperties.Prisons, ref d._Prisons);
                }
                private static global::System.Collections.IEnumerable _Prisons_GetEntityCollection(global::LightSwitchApplication.NLAddressOrderType.DetailsClass d)
                {
                    return d.ImplementationEntity.Prisons;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.NLAddressOrderType, global::LightSwitchApplication.NLAddressOrderType.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.NLAddressOrderType, global::LightSwitchApplication.NLAddressOrderType.DetailsClass, string>.Data _Name;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.NLAddressOrderType, global::LightSwitchApplication.NLAddressOrderType.DetailsClass, global::LightSwitchApplication.Prison>.Data _Prisons;
            
        }
    
        #endregion
    }
    
    #endregion
}
