

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class Contacts : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Contacts entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Contacts()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Contacts(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Contacts> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Contacts.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Contacts_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Contacts_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Contacts.DetailsClass.GetValue(this, global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.Contacts.DetailsClass.SetValue(this, global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Title
        {
            get
            {
                return global::LightSwitchApplication.Contacts.DetailsClass.GetValue(this, global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties.Title);
            }
            set
            {
                global::LightSwitchApplication.Contacts.DetailsClass.SetValue(this, global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties.Title, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Title_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Title_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Title_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string FirstName
        {
            get
            {
                return global::LightSwitchApplication.Contacts.DetailsClass.GetValue(this, global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties.FirstName);
            }
            set
            {
                global::LightSwitchApplication.Contacts.DetailsClass.SetValue(this, global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties.FirstName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FirstName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FirstName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FirstName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string LastName
        {
            get
            {
                return global::LightSwitchApplication.Contacts.DetailsClass.GetValue(this, global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties.LastName);
            }
            set
            {
                global::LightSwitchApplication.Contacts.DetailsClass.SetValue(this, global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties.LastName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LastName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LastName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LastName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Line1
        {
            get
            {
                return global::LightSwitchApplication.Contacts.DetailsClass.GetValue(this, global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties.Line1);
            }
            set
            {
                global::LightSwitchApplication.Contacts.DetailsClass.SetValue(this, global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties.Line1, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Line1_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Line1_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Line1_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Line2
        {
            get
            {
                return global::LightSwitchApplication.Contacts.DetailsClass.GetValue(this, global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties.Line2);
            }
            set
            {
                global::LightSwitchApplication.Contacts.DetailsClass.SetValue(this, global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties.Line2, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Line2_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Line2_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Line2_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Line3
        {
            get
            {
                return global::LightSwitchApplication.Contacts.DetailsClass.GetValue(this, global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties.Line3);
            }
            set
            {
                global::LightSwitchApplication.Contacts.DetailsClass.SetValue(this, global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties.Line3, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Line3_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Line3_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Line3_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Town
        {
            get
            {
                return global::LightSwitchApplication.Contacts.DetailsClass.GetValue(this, global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties.Town);
            }
            set
            {
                global::LightSwitchApplication.Contacts.DetailsClass.SetValue(this, global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties.Town, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Town_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Town_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Town_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string County
        {
            get
            {
                return global::LightSwitchApplication.Contacts.DetailsClass.GetValue(this, global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties.County);
            }
            set
            {
                global::LightSwitchApplication.Contacts.DetailsClass.SetValue(this, global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties.County, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void County_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void County_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void County_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Postcode
        {
            get
            {
                return global::LightSwitchApplication.Contacts.DetailsClass.GetValue(this, global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties.Postcode);
            }
            set
            {
                global::LightSwitchApplication.Contacts.DetailsClass.SetValue(this, global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties.Postcode, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Postcode_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Postcode_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Postcode_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string PhoneNumbers
        {
            get
            {
                return global::LightSwitchApplication.Contacts.DetailsClass.GetValue(this, global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties.PhoneNumbers);
            }
            set
            {
                global::LightSwitchApplication.Contacts.DetailsClass.SetValue(this, global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties.PhoneNumbers, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PhoneNumbers_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PhoneNumbers_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PhoneNumbers_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.ContactTypes PersonType
        {
            get
            {
                return global::LightSwitchApplication.Contacts.DetailsClass.GetValue(this, global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties.PersonType);
            }
            set
            {
                global::LightSwitchApplication.Contacts.DetailsClass.SetValue(this, global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties.PersonType, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PersonType_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PersonType_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PersonType_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Countries Country
        {
            get
            {
                return global::LightSwitchApplication.Contacts.DetailsClass.GetValue(this, global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties.Country);
            }
            set
            {
                global::LightSwitchApplication.Contacts.DetailsClass.SetValue(this, global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties.Country, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Country_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Country_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Country_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Prisoner Prisoner
        {
            get
            {
                return global::LightSwitchApplication.Contacts.DetailsClass.GetValue(this, global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties.Prisoner);
            }
            set
            {
                global::LightSwitchApplication.Contacts.DetailsClass.SetValue(this, global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties.Prisoner, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Prisoner_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Prisoner_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Prisoner_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Contacts,
                global::LightSwitchApplication.Contacts.DetailsClass,
                global::LightSwitchApplication.Contacts.DetailsClass.IImplementation,
                global::LightSwitchApplication.Contacts.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass>.Entry
                __ContactsEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass>.Entry(
                    global::LightSwitchApplication.Contacts.DetailsClass.__Contacts_CreateNew,
                    global::LightSwitchApplication.Contacts.DetailsClass.__Contacts_Created,
                    global::LightSwitchApplication.Contacts.DetailsClass.__Contacts_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Contacts __Contacts_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Contacts> es)
            {
                return new global::LightSwitchApplication.Contacts(es);
            }
            private static void __Contacts_Created(global::LightSwitchApplication.Contacts e)
            {
                e.Contacts_Created();
            }
            private static bool __Contacts_AllowSaveWithErrors(global::LightSwitchApplication.Contacts e)
            {
                bool result = false;
                e.Contacts_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Contacts.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string> Title
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties.Title) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string> FirstName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties.FirstName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string> LastName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties.LastName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string> Line1
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties.Line1) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string> Line2
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties.Line2) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string> Line3
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties.Line3) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string> Town
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties.Town) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string> County
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties.County) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string> Postcode
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties.Postcode) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string> PhoneNumbers
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties.PhoneNumbers) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, global::LightSwitchApplication.ContactTypes> PersonType
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties.PersonType) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, global::LightSwitchApplication.ContactTypes>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, global::LightSwitchApplication.Countries> Country
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties.Country) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, global::LightSwitchApplication.Countries>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, global::LightSwitchApplication.Prisoner> Prisoner
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties.Prisoner) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, global::LightSwitchApplication.Prisoner>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new string Title { get; set; }
                new string FirstName { get; set; }
                new string LastName { get; set; }
                new string Line1 { get; set; }
                new string Line2 { get; set; }
                new string Line3 { get; set; }
                new string Town { get; set; }
                new string County { get; set; }
                new string Postcode { get; set; }
                new string PhoneNumbers { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation PersonType { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Country { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Prisoner { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Contacts.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, int>.Data> c, global::LightSwitchApplication.Contacts.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Contacts e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Contacts e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Contacts.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.Contacts.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Contacts e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string>.Entry
                    Title = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string>.Entry(
                        "Title",
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Title_Stub,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Title_ComputeIsReadOnly,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Title_Validate,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Title_GetImplementationValue,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Title_SetImplementationValue,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Title_OnValueChanged);
                private static void _Title_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Contacts.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string>.Data> c, global::LightSwitchApplication.Contacts.DetailsClass d, object sf)
                {
                    c(d, ref d._Title, sf);
                }
                private static bool _Title_ComputeIsReadOnly(global::LightSwitchApplication.Contacts e)
                {
                    bool result = false;
                    e.Title_IsReadOnly(ref result);
                    return result;
                }
                private static void _Title_Validate(global::LightSwitchApplication.Contacts e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Title_Validate(r);
                }
                private static string _Title_GetImplementationValue(global::LightSwitchApplication.Contacts.DetailsClass d)
                {
                    return d.ImplementationEntity.Title;
                }
                private static void _Title_SetImplementationValue(global::LightSwitchApplication.Contacts.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Title = v;
                }
                private static void _Title_OnValueChanged(global::LightSwitchApplication.Contacts e)
                {
                    e.Title_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string>.Entry
                    FirstName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string>.Entry(
                        "FirstName",
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._FirstName_Stub,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._FirstName_ComputeIsReadOnly,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._FirstName_Validate,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._FirstName_GetImplementationValue,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._FirstName_SetImplementationValue,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._FirstName_OnValueChanged);
                private static void _FirstName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Contacts.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string>.Data> c, global::LightSwitchApplication.Contacts.DetailsClass d, object sf)
                {
                    c(d, ref d._FirstName, sf);
                }
                private static bool _FirstName_ComputeIsReadOnly(global::LightSwitchApplication.Contacts e)
                {
                    bool result = false;
                    e.FirstName_IsReadOnly(ref result);
                    return result;
                }
                private static void _FirstName_Validate(global::LightSwitchApplication.Contacts e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.FirstName_Validate(r);
                }
                private static string _FirstName_GetImplementationValue(global::LightSwitchApplication.Contacts.DetailsClass d)
                {
                    return d.ImplementationEntity.FirstName;
                }
                private static void _FirstName_SetImplementationValue(global::LightSwitchApplication.Contacts.DetailsClass d, string v)
                {
                    d.ImplementationEntity.FirstName = v;
                }
                private static void _FirstName_OnValueChanged(global::LightSwitchApplication.Contacts e)
                {
                    e.FirstName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string>.Entry
                    LastName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string>.Entry(
                        "LastName",
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._LastName_Stub,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._LastName_ComputeIsReadOnly,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._LastName_Validate,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._LastName_GetImplementationValue,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._LastName_SetImplementationValue,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._LastName_OnValueChanged);
                private static void _LastName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Contacts.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string>.Data> c, global::LightSwitchApplication.Contacts.DetailsClass d, object sf)
                {
                    c(d, ref d._LastName, sf);
                }
                private static bool _LastName_ComputeIsReadOnly(global::LightSwitchApplication.Contacts e)
                {
                    bool result = false;
                    e.LastName_IsReadOnly(ref result);
                    return result;
                }
                private static void _LastName_Validate(global::LightSwitchApplication.Contacts e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.LastName_Validate(r);
                }
                private static string _LastName_GetImplementationValue(global::LightSwitchApplication.Contacts.DetailsClass d)
                {
                    return d.ImplementationEntity.LastName;
                }
                private static void _LastName_SetImplementationValue(global::LightSwitchApplication.Contacts.DetailsClass d, string v)
                {
                    d.ImplementationEntity.LastName = v;
                }
                private static void _LastName_OnValueChanged(global::LightSwitchApplication.Contacts e)
                {
                    e.LastName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string>.Entry
                    Line1 = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string>.Entry(
                        "Line1",
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Line1_Stub,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Line1_ComputeIsReadOnly,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Line1_Validate,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Line1_GetImplementationValue,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Line1_SetImplementationValue,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Line1_OnValueChanged);
                private static void _Line1_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Contacts.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string>.Data> c, global::LightSwitchApplication.Contacts.DetailsClass d, object sf)
                {
                    c(d, ref d._Line1, sf);
                }
                private static bool _Line1_ComputeIsReadOnly(global::LightSwitchApplication.Contacts e)
                {
                    bool result = false;
                    e.Line1_IsReadOnly(ref result);
                    return result;
                }
                private static void _Line1_Validate(global::LightSwitchApplication.Contacts e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Line1_Validate(r);
                }
                private static string _Line1_GetImplementationValue(global::LightSwitchApplication.Contacts.DetailsClass d)
                {
                    return d.ImplementationEntity.Line1;
                }
                private static void _Line1_SetImplementationValue(global::LightSwitchApplication.Contacts.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Line1 = v;
                }
                private static void _Line1_OnValueChanged(global::LightSwitchApplication.Contacts e)
                {
                    e.Line1_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string>.Entry
                    Line2 = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string>.Entry(
                        "Line2",
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Line2_Stub,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Line2_ComputeIsReadOnly,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Line2_Validate,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Line2_GetImplementationValue,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Line2_SetImplementationValue,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Line2_OnValueChanged);
                private static void _Line2_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Contacts.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string>.Data> c, global::LightSwitchApplication.Contacts.DetailsClass d, object sf)
                {
                    c(d, ref d._Line2, sf);
                }
                private static bool _Line2_ComputeIsReadOnly(global::LightSwitchApplication.Contacts e)
                {
                    bool result = false;
                    e.Line2_IsReadOnly(ref result);
                    return result;
                }
                private static void _Line2_Validate(global::LightSwitchApplication.Contacts e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Line2_Validate(r);
                }
                private static string _Line2_GetImplementationValue(global::LightSwitchApplication.Contacts.DetailsClass d)
                {
                    return d.ImplementationEntity.Line2;
                }
                private static void _Line2_SetImplementationValue(global::LightSwitchApplication.Contacts.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Line2 = v;
                }
                private static void _Line2_OnValueChanged(global::LightSwitchApplication.Contacts e)
                {
                    e.Line2_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string>.Entry
                    Line3 = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string>.Entry(
                        "Line3",
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Line3_Stub,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Line3_ComputeIsReadOnly,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Line3_Validate,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Line3_GetImplementationValue,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Line3_SetImplementationValue,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Line3_OnValueChanged);
                private static void _Line3_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Contacts.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string>.Data> c, global::LightSwitchApplication.Contacts.DetailsClass d, object sf)
                {
                    c(d, ref d._Line3, sf);
                }
                private static bool _Line3_ComputeIsReadOnly(global::LightSwitchApplication.Contacts e)
                {
                    bool result = false;
                    e.Line3_IsReadOnly(ref result);
                    return result;
                }
                private static void _Line3_Validate(global::LightSwitchApplication.Contacts e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Line3_Validate(r);
                }
                private static string _Line3_GetImplementationValue(global::LightSwitchApplication.Contacts.DetailsClass d)
                {
                    return d.ImplementationEntity.Line3;
                }
                private static void _Line3_SetImplementationValue(global::LightSwitchApplication.Contacts.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Line3 = v;
                }
                private static void _Line3_OnValueChanged(global::LightSwitchApplication.Contacts e)
                {
                    e.Line3_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string>.Entry
                    Town = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string>.Entry(
                        "Town",
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Town_Stub,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Town_ComputeIsReadOnly,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Town_Validate,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Town_GetImplementationValue,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Town_SetImplementationValue,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Town_OnValueChanged);
                private static void _Town_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Contacts.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string>.Data> c, global::LightSwitchApplication.Contacts.DetailsClass d, object sf)
                {
                    c(d, ref d._Town, sf);
                }
                private static bool _Town_ComputeIsReadOnly(global::LightSwitchApplication.Contacts e)
                {
                    bool result = false;
                    e.Town_IsReadOnly(ref result);
                    return result;
                }
                private static void _Town_Validate(global::LightSwitchApplication.Contacts e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Town_Validate(r);
                }
                private static string _Town_GetImplementationValue(global::LightSwitchApplication.Contacts.DetailsClass d)
                {
                    return d.ImplementationEntity.Town;
                }
                private static void _Town_SetImplementationValue(global::LightSwitchApplication.Contacts.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Town = v;
                }
                private static void _Town_OnValueChanged(global::LightSwitchApplication.Contacts e)
                {
                    e.Town_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string>.Entry
                    County = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string>.Entry(
                        "County",
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._County_Stub,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._County_ComputeIsReadOnly,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._County_Validate,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._County_GetImplementationValue,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._County_SetImplementationValue,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._County_OnValueChanged);
                private static void _County_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Contacts.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string>.Data> c, global::LightSwitchApplication.Contacts.DetailsClass d, object sf)
                {
                    c(d, ref d._County, sf);
                }
                private static bool _County_ComputeIsReadOnly(global::LightSwitchApplication.Contacts e)
                {
                    bool result = false;
                    e.County_IsReadOnly(ref result);
                    return result;
                }
                private static void _County_Validate(global::LightSwitchApplication.Contacts e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.County_Validate(r);
                }
                private static string _County_GetImplementationValue(global::LightSwitchApplication.Contacts.DetailsClass d)
                {
                    return d.ImplementationEntity.County;
                }
                private static void _County_SetImplementationValue(global::LightSwitchApplication.Contacts.DetailsClass d, string v)
                {
                    d.ImplementationEntity.County = v;
                }
                private static void _County_OnValueChanged(global::LightSwitchApplication.Contacts e)
                {
                    e.County_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string>.Entry
                    Postcode = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string>.Entry(
                        "Postcode",
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Postcode_Stub,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Postcode_ComputeIsReadOnly,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Postcode_Validate,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Postcode_GetImplementationValue,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Postcode_SetImplementationValue,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Postcode_OnValueChanged);
                private static void _Postcode_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Contacts.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string>.Data> c, global::LightSwitchApplication.Contacts.DetailsClass d, object sf)
                {
                    c(d, ref d._Postcode, sf);
                }
                private static bool _Postcode_ComputeIsReadOnly(global::LightSwitchApplication.Contacts e)
                {
                    bool result = false;
                    e.Postcode_IsReadOnly(ref result);
                    return result;
                }
                private static void _Postcode_Validate(global::LightSwitchApplication.Contacts e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Postcode_Validate(r);
                }
                private static string _Postcode_GetImplementationValue(global::LightSwitchApplication.Contacts.DetailsClass d)
                {
                    return d.ImplementationEntity.Postcode;
                }
                private static void _Postcode_SetImplementationValue(global::LightSwitchApplication.Contacts.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Postcode = v;
                }
                private static void _Postcode_OnValueChanged(global::LightSwitchApplication.Contacts e)
                {
                    e.Postcode_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string>.Entry
                    PhoneNumbers = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string>.Entry(
                        "PhoneNumbers",
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._PhoneNumbers_Stub,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._PhoneNumbers_ComputeIsReadOnly,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._PhoneNumbers_Validate,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._PhoneNumbers_GetImplementationValue,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._PhoneNumbers_SetImplementationValue,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._PhoneNumbers_OnValueChanged);
                private static void _PhoneNumbers_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Contacts.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string>.Data> c, global::LightSwitchApplication.Contacts.DetailsClass d, object sf)
                {
                    c(d, ref d._PhoneNumbers, sf);
                }
                private static bool _PhoneNumbers_ComputeIsReadOnly(global::LightSwitchApplication.Contacts e)
                {
                    bool result = false;
                    e.PhoneNumbers_IsReadOnly(ref result);
                    return result;
                }
                private static void _PhoneNumbers_Validate(global::LightSwitchApplication.Contacts e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.PhoneNumbers_Validate(r);
                }
                private static string _PhoneNumbers_GetImplementationValue(global::LightSwitchApplication.Contacts.DetailsClass d)
                {
                    return d.ImplementationEntity.PhoneNumbers;
                }
                private static void _PhoneNumbers_SetImplementationValue(global::LightSwitchApplication.Contacts.DetailsClass d, string v)
                {
                    d.ImplementationEntity.PhoneNumbers = v;
                }
                private static void _PhoneNumbers_OnValueChanged(global::LightSwitchApplication.Contacts e)
                {
                    e.PhoneNumbers_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, global::LightSwitchApplication.ContactTypes>.Entry
                    PersonType = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, global::LightSwitchApplication.ContactTypes>.Entry(
                        "PersonType",
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._PersonType_Stub,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._PersonType_ComputeIsReadOnly,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._PersonType_Validate,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._PersonType_GetCoreImplementationValue,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._PersonType_GetImplementationValue,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._PersonType_SetImplementationValue,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._PersonType_Refresh,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._PersonType_OnValueChanged);
                private static void _PersonType_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Contacts.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, global::LightSwitchApplication.ContactTypes>.Data> c, global::LightSwitchApplication.Contacts.DetailsClass d, object sf)
                {
                    c(d, ref d._PersonType, sf);
                }
                private static bool _PersonType_ComputeIsReadOnly(global::LightSwitchApplication.Contacts e)
                {
                    bool result = false;
                    e.PersonType_IsReadOnly(ref result);
                    return result;
                }
                private static void _PersonType_Validate(global::LightSwitchApplication.Contacts e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.PersonType_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _PersonType_GetCoreImplementationValue(global::LightSwitchApplication.Contacts.DetailsClass d)
                {
                    return d.ImplementationEntity.PersonType;
                }
                private static global::LightSwitchApplication.ContactTypes _PersonType_GetImplementationValue(global::LightSwitchApplication.Contacts.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.ContactTypes, global::LightSwitchApplication.ContactTypes.DetailsClass>(global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties.PersonType, ref d._PersonType);
                }
                private static void _PersonType_SetImplementationValue(global::LightSwitchApplication.Contacts.DetailsClass d, global::LightSwitchApplication.ContactTypes v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties.PersonType, ref d._PersonType, (i, ev) => i.PersonType = ev, v);
                }
                private static void _PersonType_Refresh(global::LightSwitchApplication.Contacts.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties.PersonType, ref d._PersonType);
                }
                private static void _PersonType_OnValueChanged(global::LightSwitchApplication.Contacts e)
                {
                    e.PersonType_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, global::LightSwitchApplication.Countries>.Entry
                    Country = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, global::LightSwitchApplication.Countries>.Entry(
                        "Country",
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Country_Stub,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Country_ComputeIsReadOnly,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Country_Validate,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Country_GetCoreImplementationValue,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Country_GetImplementationValue,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Country_SetImplementationValue,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Country_Refresh,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Country_OnValueChanged);
                private static void _Country_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Contacts.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, global::LightSwitchApplication.Countries>.Data> c, global::LightSwitchApplication.Contacts.DetailsClass d, object sf)
                {
                    c(d, ref d._Country, sf);
                }
                private static bool _Country_ComputeIsReadOnly(global::LightSwitchApplication.Contacts e)
                {
                    bool result = false;
                    e.Country_IsReadOnly(ref result);
                    return result;
                }
                private static void _Country_Validate(global::LightSwitchApplication.Contacts e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Country_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Country_GetCoreImplementationValue(global::LightSwitchApplication.Contacts.DetailsClass d)
                {
                    return d.ImplementationEntity.Country;
                }
                private static global::LightSwitchApplication.Countries _Country_GetImplementationValue(global::LightSwitchApplication.Contacts.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Countries, global::LightSwitchApplication.Countries.DetailsClass>(global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties.Country, ref d._Country);
                }
                private static void _Country_SetImplementationValue(global::LightSwitchApplication.Contacts.DetailsClass d, global::LightSwitchApplication.Countries v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties.Country, ref d._Country, (i, ev) => i.Country = ev, v);
                }
                private static void _Country_Refresh(global::LightSwitchApplication.Contacts.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties.Country, ref d._Country);
                }
                private static void _Country_OnValueChanged(global::LightSwitchApplication.Contacts e)
                {
                    e.Country_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, global::LightSwitchApplication.Prisoner>.Entry
                    Prisoner = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, global::LightSwitchApplication.Prisoner>.Entry(
                        "Prisoner",
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Prisoner_Stub,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Prisoner_ComputeIsReadOnly,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Prisoner_Validate,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Prisoner_GetCoreImplementationValue,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Prisoner_GetImplementationValue,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Prisoner_SetImplementationValue,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Prisoner_Refresh,
                        global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties._Prisoner_OnValueChanged);
                private static void _Prisoner_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Contacts.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, global::LightSwitchApplication.Prisoner>.Data> c, global::LightSwitchApplication.Contacts.DetailsClass d, object sf)
                {
                    c(d, ref d._Prisoner, sf);
                }
                private static bool _Prisoner_ComputeIsReadOnly(global::LightSwitchApplication.Contacts e)
                {
                    bool result = false;
                    e.Prisoner_IsReadOnly(ref result);
                    return result;
                }
                private static void _Prisoner_Validate(global::LightSwitchApplication.Contacts e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Prisoner_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Prisoner_GetCoreImplementationValue(global::LightSwitchApplication.Contacts.DetailsClass d)
                {
                    return d.ImplementationEntity.Prisoner;
                }
                private static global::LightSwitchApplication.Prisoner _Prisoner_GetImplementationValue(global::LightSwitchApplication.Contacts.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Prisoner, global::LightSwitchApplication.Prisoner.DetailsClass>(global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties.Prisoner, ref d._Prisoner);
                }
                private static void _Prisoner_SetImplementationValue(global::LightSwitchApplication.Contacts.DetailsClass d, global::LightSwitchApplication.Prisoner v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties.Prisoner, ref d._Prisoner, (i, ev) => i.Prisoner = ev, v);
                }
                private static void _Prisoner_Refresh(global::LightSwitchApplication.Contacts.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Contacts.DetailsClass.PropertySetProperties.Prisoner, ref d._Prisoner);
                }
                private static void _Prisoner_OnValueChanged(global::LightSwitchApplication.Contacts e)
                {
                    e.Prisoner_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string>.Data _Title;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string>.Data _FirstName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string>.Data _LastName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string>.Data _Line1;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string>.Data _Line2;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string>.Data _Line3;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string>.Data _Town;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string>.Data _County;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string>.Data _Postcode;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, string>.Data _PhoneNumbers;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, global::LightSwitchApplication.ContactTypes>.Data _PersonType;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, global::LightSwitchApplication.Countries>.Data _Country;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Contacts, global::LightSwitchApplication.Contacts.DetailsClass, global::LightSwitchApplication.Prisoner>.Data _Prisoner;
            
        }
    
        #endregion
    }
    
    #endregion
}
