

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class MailCode : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.MailCode, global::LightSwitchApplication.MailCode.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the MailCode entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public MailCode()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public MailCode(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.MailCode> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.MailCode.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MailCode_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MailCode_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.MailCode.DetailsClass.GetValue(this, global::LightSwitchApplication.MailCode.DetailsClass.PropertySetProperties.Id);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Name
        {
            get
            {
                return global::LightSwitchApplication.MailCode.DetailsClass.GetValue(this, global::LightSwitchApplication.MailCode.DetailsClass.PropertySetProperties.Name);
            }
            set
            {
                global::LightSwitchApplication.MailCode.DetailsClass.SetValue(this, global::LightSwitchApplication.MailCode.DetailsClass.PropertySetProperties.Name, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Code1
        {
            get
            {
                return global::LightSwitchApplication.MailCode.DetailsClass.GetValue(this, global::LightSwitchApplication.MailCode.DetailsClass.PropertySetProperties.Code1);
            }
            set
            {
                global::LightSwitchApplication.MailCode.DetailsClass.SetValue(this, global::LightSwitchApplication.MailCode.DetailsClass.PropertySetProperties.Code1, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Code1_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Code1_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Code1_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Contact> Contacts
        {
            get
            {
                return global::LightSwitchApplication.MailCode.DetailsClass.GetValue(this, global::LightSwitchApplication.MailCode.DetailsClass.PropertySetProperties.Contacts);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Contact> ContactsQuery
        {
            get
            {
                return global::LightSwitchApplication.MailCode.DetailsClass.GetQuery(this, global::LightSwitchApplication.MailCode.DetailsClass.PropertySetProperties.Contacts);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.MailCode,
                global::LightSwitchApplication.MailCode.DetailsClass,
                global::LightSwitchApplication.MailCode.DetailsClass.IImplementation,
                global::LightSwitchApplication.MailCode.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.MailCode, global::LightSwitchApplication.MailCode.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.MailCode, global::LightSwitchApplication.MailCode.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.MailCode.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.MailCode, global::LightSwitchApplication.MailCode.DetailsClass>.Entry
                __MailCodeEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.MailCode, global::LightSwitchApplication.MailCode.DetailsClass>.Entry(
                    global::LightSwitchApplication.MailCode.DetailsClass.__MailCode_CreateNew,
                    global::LightSwitchApplication.MailCode.DetailsClass.__MailCode_Created,
                    global::LightSwitchApplication.MailCode.DetailsClass.__MailCode_AllowSaveWithErrors);
            private static global::LightSwitchApplication.MailCode __MailCode_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.MailCode> es)
            {
                return new global::LightSwitchApplication.MailCode(es);
            }
            private static void __MailCode_Created(global::LightSwitchApplication.MailCode e)
            {
                e.MailCode_Created();
            }
            private static bool __MailCode_AllowSaveWithErrors(global::LightSwitchApplication.MailCode e)
            {
                bool result = false;
                e.MailCode_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.MailCode, global::LightSwitchApplication.MailCode.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.MailCode, global::LightSwitchApplication.MailCode.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.MailCode.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.MailCode, global::LightSwitchApplication.MailCode.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailCode, global::LightSwitchApplication.MailCode.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.MailCode.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailCode, global::LightSwitchApplication.MailCode.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailCode, global::LightSwitchApplication.MailCode.DetailsClass, string> Name
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.MailCode.DetailsClass.PropertySetProperties.Name) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailCode, global::LightSwitchApplication.MailCode.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailCode, global::LightSwitchApplication.MailCode.DetailsClass, string> Code1
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.MailCode.DetailsClass.PropertySetProperties.Code1) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailCode, global::LightSwitchApplication.MailCode.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.MailCode, global::LightSwitchApplication.MailCode.DetailsClass, global::LightSwitchApplication.Contact> Contacts
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.MailCode.DetailsClass.PropertySetProperties.Contacts) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.MailCode, global::LightSwitchApplication.MailCode.DetailsClass, global::LightSwitchApplication.Contact>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; }
                new string Name { get; set; }
                new string Code1 { get; set; }
                new global::System.Collections.IEnumerable Contacts { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailCode, global::LightSwitchApplication.MailCode.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailCode, global::LightSwitchApplication.MailCode.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.MailCode.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.MailCode.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.MailCode.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.MailCode.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.MailCode.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.MailCode.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailCode, global::LightSwitchApplication.MailCode.DetailsClass, int>.Data> c, global::LightSwitchApplication.MailCode.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.MailCode e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.MailCode e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.MailCode.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.MailCode e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailCode, global::LightSwitchApplication.MailCode.DetailsClass, string>.Entry
                    Name = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailCode, global::LightSwitchApplication.MailCode.DetailsClass, string>.Entry(
                        "Name",
                        global::LightSwitchApplication.MailCode.DetailsClass.PropertySetProperties._Name_Stub,
                        global::LightSwitchApplication.MailCode.DetailsClass.PropertySetProperties._Name_ComputeIsReadOnly,
                        global::LightSwitchApplication.MailCode.DetailsClass.PropertySetProperties._Name_Validate,
                        global::LightSwitchApplication.MailCode.DetailsClass.PropertySetProperties._Name_GetImplementationValue,
                        global::LightSwitchApplication.MailCode.DetailsClass.PropertySetProperties._Name_SetImplementationValue,
                        global::LightSwitchApplication.MailCode.DetailsClass.PropertySetProperties._Name_OnValueChanged);
                private static void _Name_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.MailCode.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailCode, global::LightSwitchApplication.MailCode.DetailsClass, string>.Data> c, global::LightSwitchApplication.MailCode.DetailsClass d, object sf)
                {
                    c(d, ref d._Name, sf);
                }
                private static bool _Name_ComputeIsReadOnly(global::LightSwitchApplication.MailCode e)
                {
                    bool result = false;
                    e.Name_IsReadOnly(ref result);
                    return result;
                }
                private static void _Name_Validate(global::LightSwitchApplication.MailCode e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Name_Validate(r);
                }
                private static string _Name_GetImplementationValue(global::LightSwitchApplication.MailCode.DetailsClass d)
                {
                    return d.ImplementationEntity.Name;
                }
                private static void _Name_SetImplementationValue(global::LightSwitchApplication.MailCode.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Name = v;
                }
                private static void _Name_OnValueChanged(global::LightSwitchApplication.MailCode e)
                {
                    e.Name_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailCode, global::LightSwitchApplication.MailCode.DetailsClass, string>.Entry
                    Code1 = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailCode, global::LightSwitchApplication.MailCode.DetailsClass, string>.Entry(
                        "Code1",
                        global::LightSwitchApplication.MailCode.DetailsClass.PropertySetProperties._Code1_Stub,
                        global::LightSwitchApplication.MailCode.DetailsClass.PropertySetProperties._Code1_ComputeIsReadOnly,
                        global::LightSwitchApplication.MailCode.DetailsClass.PropertySetProperties._Code1_Validate,
                        global::LightSwitchApplication.MailCode.DetailsClass.PropertySetProperties._Code1_GetImplementationValue,
                        global::LightSwitchApplication.MailCode.DetailsClass.PropertySetProperties._Code1_SetImplementationValue,
                        global::LightSwitchApplication.MailCode.DetailsClass.PropertySetProperties._Code1_OnValueChanged);
                private static void _Code1_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.MailCode.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailCode, global::LightSwitchApplication.MailCode.DetailsClass, string>.Data> c, global::LightSwitchApplication.MailCode.DetailsClass d, object sf)
                {
                    c(d, ref d._Code1, sf);
                }
                private static bool _Code1_ComputeIsReadOnly(global::LightSwitchApplication.MailCode e)
                {
                    bool result = false;
                    e.Code1_IsReadOnly(ref result);
                    return result;
                }
                private static void _Code1_Validate(global::LightSwitchApplication.MailCode e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Code1_Validate(r);
                }
                private static string _Code1_GetImplementationValue(global::LightSwitchApplication.MailCode.DetailsClass d)
                {
                    return d.ImplementationEntity.Code1;
                }
                private static void _Code1_SetImplementationValue(global::LightSwitchApplication.MailCode.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Code1 = v;
                }
                private static void _Code1_OnValueChanged(global::LightSwitchApplication.MailCode e)
                {
                    e.Code1_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.MailCode, global::LightSwitchApplication.MailCode.DetailsClass, global::LightSwitchApplication.Contact>.Entry
                    Contacts = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.MailCode, global::LightSwitchApplication.MailCode.DetailsClass, global::LightSwitchApplication.Contact>.Entry(
                        "Contacts",
                        global::LightSwitchApplication.MailCode.DetailsClass.PropertySetProperties._Contacts_Stub,
                        global::LightSwitchApplication.MailCode.DetailsClass.PropertySetProperties._Contacts_GetReferencedEntities,
                        global::LightSwitchApplication.MailCode.DetailsClass.PropertySetProperties._Contacts_GetEntityCollection);
                private static void _Contacts_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.MailCode.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.MailCode, global::LightSwitchApplication.MailCode.DetailsClass, global::LightSwitchApplication.Contact>.Data> c, global::LightSwitchApplication.MailCode.DetailsClass d, object sf)
                {
                    c(d, ref d._Contacts, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Contact> _Contacts_GetReferencedEntities(global::LightSwitchApplication.MailCode.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Contact, global::LightSwitchApplication.Contact.DetailsClass>(global::LightSwitchApplication.MailCode.DetailsClass.PropertySetProperties.Contacts, ref d._Contacts);
                }
                private static global::System.Collections.IEnumerable _Contacts_GetEntityCollection(global::LightSwitchApplication.MailCode.DetailsClass d)
                {
                    return d.ImplementationEntity.Contacts;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailCode, global::LightSwitchApplication.MailCode.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailCode, global::LightSwitchApplication.MailCode.DetailsClass, string>.Data _Name;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailCode, global::LightSwitchApplication.MailCode.DetailsClass, string>.Data _Code1;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.MailCode, global::LightSwitchApplication.MailCode.DetailsClass, global::LightSwitchApplication.Contact>.Data _Contacts;
            
        }
    
        #endregion
    }
    
    #endregion
}
