

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class ResponseType : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.ResponseType, global::LightSwitchApplication.ResponseType.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the ResponseType entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ResponseType()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ResponseType(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.ResponseType> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.ResponseType.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ResponseType_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ResponseType_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.ResponseType.DetailsClass.GetValue(this, global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties.Id);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Response
        {
            get
            {
                return global::LightSwitchApplication.ResponseType.DetailsClass.GetValue(this, global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties.Response);
            }
            set
            {
                global::LightSwitchApplication.ResponseType.DetailsClass.SetValue(this, global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties.Response, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Response_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Response_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Response_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<double> Cost
        {
            get
            {
                return global::LightSwitchApplication.ResponseType.DetailsClass.GetValue(this, global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties.Cost);
            }
            set
            {
                global::LightSwitchApplication.ResponseType.DetailsClass.SetValue(this, global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties.Cost, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Cost_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Cost_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Cost_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Destination
        {
            get
            {
                return global::LightSwitchApplication.ResponseType.DetailsClass.GetValue(this, global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties.Destination);
            }
            set
            {
                global::LightSwitchApplication.ResponseType.DetailsClass.SetValue(this, global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties.Destination, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Destination_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Destination_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Destination_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<double> Postage
        {
            get
            {
                return global::LightSwitchApplication.ResponseType.DetailsClass.GetValue(this, global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties.Postage);
            }
            set
            {
                global::LightSwitchApplication.ResponseType.DetailsClass.SetValue(this, global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties.Postage, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Postage_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Postage_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Postage_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<double> Stationary
        {
            get
            {
                return global::LightSwitchApplication.ResponseType.DetailsClass.GetValue(this, global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties.Stationary);
            }
            set
            {
                global::LightSwitchApplication.ResponseType.DetailsClass.SetValue(this, global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties.Stationary, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Stationary_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Stationary_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Stationary_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Corresp> Corresps
        {
            get
            {
                return global::LightSwitchApplication.ResponseType.DetailsClass.GetValue(this, global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties.Corresps);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Corresp> CorrespsQuery
        {
            get
            {
                return global::LightSwitchApplication.ResponseType.DetailsClass.GetQuery(this, global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties.Corresps);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.ResponseType,
                global::LightSwitchApplication.ResponseType.DetailsClass,
                global::LightSwitchApplication.ResponseType.DetailsClass.IImplementation,
                global::LightSwitchApplication.ResponseType.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.ResponseType, global::LightSwitchApplication.ResponseType.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.ResponseType, global::LightSwitchApplication.ResponseType.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.ResponseType, global::LightSwitchApplication.ResponseType.DetailsClass>.Entry
                __ResponseTypeEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.ResponseType, global::LightSwitchApplication.ResponseType.DetailsClass>.Entry(
                    global::LightSwitchApplication.ResponseType.DetailsClass.__ResponseType_CreateNew,
                    global::LightSwitchApplication.ResponseType.DetailsClass.__ResponseType_Created,
                    global::LightSwitchApplication.ResponseType.DetailsClass.__ResponseType_AllowSaveWithErrors);
            private static global::LightSwitchApplication.ResponseType __ResponseType_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.ResponseType> es)
            {
                return new global::LightSwitchApplication.ResponseType(es);
            }
            private static void __ResponseType_Created(global::LightSwitchApplication.ResponseType e)
            {
                e.ResponseType_Created();
            }
            private static bool __ResponseType_AllowSaveWithErrors(global::LightSwitchApplication.ResponseType e)
            {
                bool result = false;
                e.ResponseType_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.ResponseType, global::LightSwitchApplication.ResponseType.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.ResponseType, global::LightSwitchApplication.ResponseType.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.ResponseType.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.ResponseType, global::LightSwitchApplication.ResponseType.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponseType, global::LightSwitchApplication.ResponseType.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponseType, global::LightSwitchApplication.ResponseType.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponseType, global::LightSwitchApplication.ResponseType.DetailsClass, string> Response
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties.Response) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponseType, global::LightSwitchApplication.ResponseType.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponseType, global::LightSwitchApplication.ResponseType.DetailsClass, global::System.Nullable<double>> Cost
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties.Cost) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponseType, global::LightSwitchApplication.ResponseType.DetailsClass, global::System.Nullable<double>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponseType, global::LightSwitchApplication.ResponseType.DetailsClass, string> Destination
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties.Destination) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponseType, global::LightSwitchApplication.ResponseType.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponseType, global::LightSwitchApplication.ResponseType.DetailsClass, global::System.Nullable<double>> Postage
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties.Postage) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponseType, global::LightSwitchApplication.ResponseType.DetailsClass, global::System.Nullable<double>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponseType, global::LightSwitchApplication.ResponseType.DetailsClass, global::System.Nullable<double>> Stationary
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties.Stationary) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponseType, global::LightSwitchApplication.ResponseType.DetailsClass, global::System.Nullable<double>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ResponseType, global::LightSwitchApplication.ResponseType.DetailsClass, global::LightSwitchApplication.Corresp> Corresps
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties.Corresps) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ResponseType, global::LightSwitchApplication.ResponseType.DetailsClass, global::LightSwitchApplication.Corresp>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; }
                new string Response { get; set; }
                new global::System.Nullable<double> Cost { get; set; }
                new string Destination { get; set; }
                new global::System.Nullable<double> Postage { get; set; }
                new global::System.Nullable<double> Stationary { get; set; }
                new global::System.Collections.IEnumerable Corresps { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponseType, global::LightSwitchApplication.ResponseType.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponseType, global::LightSwitchApplication.ResponseType.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ResponseType.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponseType, global::LightSwitchApplication.ResponseType.DetailsClass, int>.Data> c, global::LightSwitchApplication.ResponseType.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.ResponseType e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.ResponseType e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.ResponseType.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.ResponseType e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponseType, global::LightSwitchApplication.ResponseType.DetailsClass, string>.Entry
                    Response = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponseType, global::LightSwitchApplication.ResponseType.DetailsClass, string>.Entry(
                        "Response",
                        global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties._Response_Stub,
                        global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties._Response_ComputeIsReadOnly,
                        global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties._Response_Validate,
                        global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties._Response_GetImplementationValue,
                        global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties._Response_SetImplementationValue,
                        global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties._Response_OnValueChanged);
                private static void _Response_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ResponseType.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponseType, global::LightSwitchApplication.ResponseType.DetailsClass, string>.Data> c, global::LightSwitchApplication.ResponseType.DetailsClass d, object sf)
                {
                    c(d, ref d._Response, sf);
                }
                private static bool _Response_ComputeIsReadOnly(global::LightSwitchApplication.ResponseType e)
                {
                    bool result = false;
                    e.Response_IsReadOnly(ref result);
                    return result;
                }
                private static void _Response_Validate(global::LightSwitchApplication.ResponseType e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Response_Validate(r);
                }
                private static string _Response_GetImplementationValue(global::LightSwitchApplication.ResponseType.DetailsClass d)
                {
                    return d.ImplementationEntity.Response;
                }
                private static void _Response_SetImplementationValue(global::LightSwitchApplication.ResponseType.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Response = v;
                }
                private static void _Response_OnValueChanged(global::LightSwitchApplication.ResponseType e)
                {
                    e.Response_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponseType, global::LightSwitchApplication.ResponseType.DetailsClass, global::System.Nullable<double>>.Entry
                    Cost = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponseType, global::LightSwitchApplication.ResponseType.DetailsClass, global::System.Nullable<double>>.Entry(
                        "Cost",
                        global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties._Cost_Stub,
                        global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties._Cost_ComputeIsReadOnly,
                        global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties._Cost_Validate,
                        global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties._Cost_GetImplementationValue,
                        global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties._Cost_SetImplementationValue,
                        global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties._Cost_OnValueChanged);
                private static void _Cost_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ResponseType.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponseType, global::LightSwitchApplication.ResponseType.DetailsClass, global::System.Nullable<double>>.Data> c, global::LightSwitchApplication.ResponseType.DetailsClass d, object sf)
                {
                    c(d, ref d._Cost, sf);
                }
                private static bool _Cost_ComputeIsReadOnly(global::LightSwitchApplication.ResponseType e)
                {
                    bool result = false;
                    e.Cost_IsReadOnly(ref result);
                    return result;
                }
                private static void _Cost_Validate(global::LightSwitchApplication.ResponseType e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Cost_Validate(r);
                }
                private static global::System.Nullable<double> _Cost_GetImplementationValue(global::LightSwitchApplication.ResponseType.DetailsClass d)
                {
                    return d.ImplementationEntity.Cost;
                }
                private static void _Cost_SetImplementationValue(global::LightSwitchApplication.ResponseType.DetailsClass d, global::System.Nullable<double> v)
                {
                    d.ImplementationEntity.Cost = v;
                }
                private static void _Cost_OnValueChanged(global::LightSwitchApplication.ResponseType e)
                {
                    e.Cost_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponseType, global::LightSwitchApplication.ResponseType.DetailsClass, string>.Entry
                    Destination = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponseType, global::LightSwitchApplication.ResponseType.DetailsClass, string>.Entry(
                        "Destination",
                        global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties._Destination_Stub,
                        global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties._Destination_ComputeIsReadOnly,
                        global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties._Destination_Validate,
                        global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties._Destination_GetImplementationValue,
                        global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties._Destination_SetImplementationValue,
                        global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties._Destination_OnValueChanged);
                private static void _Destination_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ResponseType.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponseType, global::LightSwitchApplication.ResponseType.DetailsClass, string>.Data> c, global::LightSwitchApplication.ResponseType.DetailsClass d, object sf)
                {
                    c(d, ref d._Destination, sf);
                }
                private static bool _Destination_ComputeIsReadOnly(global::LightSwitchApplication.ResponseType e)
                {
                    bool result = false;
                    e.Destination_IsReadOnly(ref result);
                    return result;
                }
                private static void _Destination_Validate(global::LightSwitchApplication.ResponseType e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Destination_Validate(r);
                }
                private static string _Destination_GetImplementationValue(global::LightSwitchApplication.ResponseType.DetailsClass d)
                {
                    return d.ImplementationEntity.Destination;
                }
                private static void _Destination_SetImplementationValue(global::LightSwitchApplication.ResponseType.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Destination = v;
                }
                private static void _Destination_OnValueChanged(global::LightSwitchApplication.ResponseType e)
                {
                    e.Destination_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponseType, global::LightSwitchApplication.ResponseType.DetailsClass, global::System.Nullable<double>>.Entry
                    Postage = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponseType, global::LightSwitchApplication.ResponseType.DetailsClass, global::System.Nullable<double>>.Entry(
                        "Postage",
                        global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties._Postage_Stub,
                        global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties._Postage_ComputeIsReadOnly,
                        global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties._Postage_Validate,
                        global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties._Postage_GetImplementationValue,
                        global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties._Postage_SetImplementationValue,
                        global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties._Postage_OnValueChanged);
                private static void _Postage_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ResponseType.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponseType, global::LightSwitchApplication.ResponseType.DetailsClass, global::System.Nullable<double>>.Data> c, global::LightSwitchApplication.ResponseType.DetailsClass d, object sf)
                {
                    c(d, ref d._Postage, sf);
                }
                private static bool _Postage_ComputeIsReadOnly(global::LightSwitchApplication.ResponseType e)
                {
                    bool result = false;
                    e.Postage_IsReadOnly(ref result);
                    return result;
                }
                private static void _Postage_Validate(global::LightSwitchApplication.ResponseType e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Postage_Validate(r);
                }
                private static global::System.Nullable<double> _Postage_GetImplementationValue(global::LightSwitchApplication.ResponseType.DetailsClass d)
                {
                    return d.ImplementationEntity.Postage;
                }
                private static void _Postage_SetImplementationValue(global::LightSwitchApplication.ResponseType.DetailsClass d, global::System.Nullable<double> v)
                {
                    d.ImplementationEntity.Postage = v;
                }
                private static void _Postage_OnValueChanged(global::LightSwitchApplication.ResponseType e)
                {
                    e.Postage_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponseType, global::LightSwitchApplication.ResponseType.DetailsClass, global::System.Nullable<double>>.Entry
                    Stationary = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponseType, global::LightSwitchApplication.ResponseType.DetailsClass, global::System.Nullable<double>>.Entry(
                        "Stationary",
                        global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties._Stationary_Stub,
                        global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties._Stationary_ComputeIsReadOnly,
                        global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties._Stationary_Validate,
                        global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties._Stationary_GetImplementationValue,
                        global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties._Stationary_SetImplementationValue,
                        global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties._Stationary_OnValueChanged);
                private static void _Stationary_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ResponseType.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponseType, global::LightSwitchApplication.ResponseType.DetailsClass, global::System.Nullable<double>>.Data> c, global::LightSwitchApplication.ResponseType.DetailsClass d, object sf)
                {
                    c(d, ref d._Stationary, sf);
                }
                private static bool _Stationary_ComputeIsReadOnly(global::LightSwitchApplication.ResponseType e)
                {
                    bool result = false;
                    e.Stationary_IsReadOnly(ref result);
                    return result;
                }
                private static void _Stationary_Validate(global::LightSwitchApplication.ResponseType e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Stationary_Validate(r);
                }
                private static global::System.Nullable<double> _Stationary_GetImplementationValue(global::LightSwitchApplication.ResponseType.DetailsClass d)
                {
                    return d.ImplementationEntity.Stationary;
                }
                private static void _Stationary_SetImplementationValue(global::LightSwitchApplication.ResponseType.DetailsClass d, global::System.Nullable<double> v)
                {
                    d.ImplementationEntity.Stationary = v;
                }
                private static void _Stationary_OnValueChanged(global::LightSwitchApplication.ResponseType e)
                {
                    e.Stationary_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ResponseType, global::LightSwitchApplication.ResponseType.DetailsClass, global::LightSwitchApplication.Corresp>.Entry
                    Corresps = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ResponseType, global::LightSwitchApplication.ResponseType.DetailsClass, global::LightSwitchApplication.Corresp>.Entry(
                        "Corresps",
                        global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties._Corresps_Stub,
                        global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties._Corresps_GetReferencedEntities,
                        global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties._Corresps_GetEntityCollection);
                private static void _Corresps_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ResponseType.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ResponseType, global::LightSwitchApplication.ResponseType.DetailsClass, global::LightSwitchApplication.Corresp>.Data> c, global::LightSwitchApplication.ResponseType.DetailsClass d, object sf)
                {
                    c(d, ref d._Corresps, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Corresp> _Corresps_GetReferencedEntities(global::LightSwitchApplication.ResponseType.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Corresp, global::LightSwitchApplication.Corresp.DetailsClass>(global::LightSwitchApplication.ResponseType.DetailsClass.PropertySetProperties.Corresps, ref d._Corresps);
                }
                private static global::System.Collections.IEnumerable _Corresps_GetEntityCollection(global::LightSwitchApplication.ResponseType.DetailsClass d)
                {
                    return d.ImplementationEntity.Corresps;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponseType, global::LightSwitchApplication.ResponseType.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponseType, global::LightSwitchApplication.ResponseType.DetailsClass, string>.Data _Response;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponseType, global::LightSwitchApplication.ResponseType.DetailsClass, global::System.Nullable<double>>.Data _Cost;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponseType, global::LightSwitchApplication.ResponseType.DetailsClass, string>.Data _Destination;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponseType, global::LightSwitchApplication.ResponseType.DetailsClass, global::System.Nullable<double>>.Data _Postage;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponseType, global::LightSwitchApplication.ResponseType.DetailsClass, global::System.Nullable<double>>.Data _Stationary;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ResponseType, global::LightSwitchApplication.ResponseType.DetailsClass, global::LightSwitchApplication.Corresp>.Data _Corresps;
            
        }
    
        #endregion
    }
    
    #endregion
}
