

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class InstitutionType : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.InstitutionType, global::LightSwitchApplication.InstitutionType.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the InstitutionType entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public InstitutionType()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public InstitutionType(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.InstitutionType> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.InstitutionType.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void InstitutionType_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void InstitutionType_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.InstitutionType.DetailsClass.GetValue(this, global::LightSwitchApplication.InstitutionType.DetailsClass.PropertySetProperties.Id);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Name
        {
            get
            {
                return global::LightSwitchApplication.InstitutionType.DetailsClass.GetValue(this, global::LightSwitchApplication.InstitutionType.DetailsClass.PropertySetProperties.Name);
            }
            set
            {
                global::LightSwitchApplication.InstitutionType.DetailsClass.SetValue(this, global::LightSwitchApplication.InstitutionType.DetailsClass.PropertySetProperties.Name, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ShortCode
        {
            get
            {
                return global::LightSwitchApplication.InstitutionType.DetailsClass.GetValue(this, global::LightSwitchApplication.InstitutionType.DetailsClass.PropertySetProperties.ShortCode);
            }
            set
            {
                global::LightSwitchApplication.InstitutionType.DetailsClass.SetValue(this, global::LightSwitchApplication.InstitutionType.DetailsClass.PropertySetProperties.ShortCode, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ShortCode_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ShortCode_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ShortCode_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.InstitutionType,
                global::LightSwitchApplication.InstitutionType.DetailsClass,
                global::LightSwitchApplication.InstitutionType.DetailsClass.IImplementation,
                global::LightSwitchApplication.InstitutionType.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.InstitutionType, global::LightSwitchApplication.InstitutionType.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.InstitutionType, global::LightSwitchApplication.InstitutionType.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.InstitutionType.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.InstitutionType, global::LightSwitchApplication.InstitutionType.DetailsClass>.Entry
                __InstitutionTypeEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.InstitutionType, global::LightSwitchApplication.InstitutionType.DetailsClass>.Entry(
                    global::LightSwitchApplication.InstitutionType.DetailsClass.__InstitutionType_CreateNew,
                    global::LightSwitchApplication.InstitutionType.DetailsClass.__InstitutionType_Created,
                    global::LightSwitchApplication.InstitutionType.DetailsClass.__InstitutionType_AllowSaveWithErrors);
            private static global::LightSwitchApplication.InstitutionType __InstitutionType_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.InstitutionType> es)
            {
                return new global::LightSwitchApplication.InstitutionType(es);
            }
            private static void __InstitutionType_Created(global::LightSwitchApplication.InstitutionType e)
            {
                e.InstitutionType_Created();
            }
            private static bool __InstitutionType_AllowSaveWithErrors(global::LightSwitchApplication.InstitutionType e)
            {
                bool result = false;
                e.InstitutionType_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.InstitutionType, global::LightSwitchApplication.InstitutionType.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.InstitutionType, global::LightSwitchApplication.InstitutionType.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.InstitutionType.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.InstitutionType, global::LightSwitchApplication.InstitutionType.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.InstitutionType, global::LightSwitchApplication.InstitutionType.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.InstitutionType.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.InstitutionType, global::LightSwitchApplication.InstitutionType.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.InstitutionType, global::LightSwitchApplication.InstitutionType.DetailsClass, string> Name
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.InstitutionType.DetailsClass.PropertySetProperties.Name) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.InstitutionType, global::LightSwitchApplication.InstitutionType.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.InstitutionType, global::LightSwitchApplication.InstitutionType.DetailsClass, string> ShortCode
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.InstitutionType.DetailsClass.PropertySetProperties.ShortCode) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.InstitutionType, global::LightSwitchApplication.InstitutionType.DetailsClass, string>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; }
                new string Name { get; set; }
                new string ShortCode { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.InstitutionType, global::LightSwitchApplication.InstitutionType.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.InstitutionType, global::LightSwitchApplication.InstitutionType.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.InstitutionType.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.InstitutionType.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.InstitutionType.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.InstitutionType.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.InstitutionType.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.InstitutionType.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.InstitutionType, global::LightSwitchApplication.InstitutionType.DetailsClass, int>.Data> c, global::LightSwitchApplication.InstitutionType.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.InstitutionType e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.InstitutionType e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.InstitutionType.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.InstitutionType e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.InstitutionType, global::LightSwitchApplication.InstitutionType.DetailsClass, string>.Entry
                    Name = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.InstitutionType, global::LightSwitchApplication.InstitutionType.DetailsClass, string>.Entry(
                        "Name",
                        global::LightSwitchApplication.InstitutionType.DetailsClass.PropertySetProperties._Name_Stub,
                        global::LightSwitchApplication.InstitutionType.DetailsClass.PropertySetProperties._Name_ComputeIsReadOnly,
                        global::LightSwitchApplication.InstitutionType.DetailsClass.PropertySetProperties._Name_Validate,
                        global::LightSwitchApplication.InstitutionType.DetailsClass.PropertySetProperties._Name_GetImplementationValue,
                        global::LightSwitchApplication.InstitutionType.DetailsClass.PropertySetProperties._Name_SetImplementationValue,
                        global::LightSwitchApplication.InstitutionType.DetailsClass.PropertySetProperties._Name_OnValueChanged);
                private static void _Name_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.InstitutionType.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.InstitutionType, global::LightSwitchApplication.InstitutionType.DetailsClass, string>.Data> c, global::LightSwitchApplication.InstitutionType.DetailsClass d, object sf)
                {
                    c(d, ref d._Name, sf);
                }
                private static bool _Name_ComputeIsReadOnly(global::LightSwitchApplication.InstitutionType e)
                {
                    bool result = false;
                    e.Name_IsReadOnly(ref result);
                    return result;
                }
                private static void _Name_Validate(global::LightSwitchApplication.InstitutionType e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Name_Validate(r);
                }
                private static string _Name_GetImplementationValue(global::LightSwitchApplication.InstitutionType.DetailsClass d)
                {
                    return d.ImplementationEntity.Name;
                }
                private static void _Name_SetImplementationValue(global::LightSwitchApplication.InstitutionType.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Name = v;
                }
                private static void _Name_OnValueChanged(global::LightSwitchApplication.InstitutionType e)
                {
                    e.Name_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.InstitutionType, global::LightSwitchApplication.InstitutionType.DetailsClass, string>.Entry
                    ShortCode = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.InstitutionType, global::LightSwitchApplication.InstitutionType.DetailsClass, string>.Entry(
                        "ShortCode",
                        global::LightSwitchApplication.InstitutionType.DetailsClass.PropertySetProperties._ShortCode_Stub,
                        global::LightSwitchApplication.InstitutionType.DetailsClass.PropertySetProperties._ShortCode_ComputeIsReadOnly,
                        global::LightSwitchApplication.InstitutionType.DetailsClass.PropertySetProperties._ShortCode_Validate,
                        global::LightSwitchApplication.InstitutionType.DetailsClass.PropertySetProperties._ShortCode_GetImplementationValue,
                        global::LightSwitchApplication.InstitutionType.DetailsClass.PropertySetProperties._ShortCode_SetImplementationValue,
                        global::LightSwitchApplication.InstitutionType.DetailsClass.PropertySetProperties._ShortCode_OnValueChanged);
                private static void _ShortCode_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.InstitutionType.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.InstitutionType, global::LightSwitchApplication.InstitutionType.DetailsClass, string>.Data> c, global::LightSwitchApplication.InstitutionType.DetailsClass d, object sf)
                {
                    c(d, ref d._ShortCode, sf);
                }
                private static bool _ShortCode_ComputeIsReadOnly(global::LightSwitchApplication.InstitutionType e)
                {
                    bool result = false;
                    e.ShortCode_IsReadOnly(ref result);
                    return result;
                }
                private static void _ShortCode_Validate(global::LightSwitchApplication.InstitutionType e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ShortCode_Validate(r);
                }
                private static string _ShortCode_GetImplementationValue(global::LightSwitchApplication.InstitutionType.DetailsClass d)
                {
                    return d.ImplementationEntity.ShortCode;
                }
                private static void _ShortCode_SetImplementationValue(global::LightSwitchApplication.InstitutionType.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ShortCode = v;
                }
                private static void _ShortCode_OnValueChanged(global::LightSwitchApplication.InstitutionType e)
                {
                    e.ShortCode_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.InstitutionType, global::LightSwitchApplication.InstitutionType.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.InstitutionType, global::LightSwitchApplication.InstitutionType.DetailsClass, string>.Data _Name;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.InstitutionType, global::LightSwitchApplication.InstitutionType.DetailsClass, string>.Data _ShortCode;
            
        }
    
        #endregion
    }
    
    #endregion
}
